version: '3'
services:
  redis:
    image: "redis:alpine"
    command: ["redis-server","--requirepass","foobared"]
    ports:
      - "6379:6379"

  mongo:
    image: "mongo:latest"
    container_name: "mighty-mongo"
    ports:
      - "27017:27017"
