version: '3'
services:
  redis:
    image: "redis:alpine"
    command: ["redis-server","--requirepass","foobared"]
    ports:
      - "6379:6379"

  mongo:
    image: "mongo:latest"
    container_name: "mighty-mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: sindu
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: expresshauliers
    restart: always
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
